### ISSUE TITLE
Message Tab - organize the messages nicely

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/SentryMobile#61]
Design:
1- The message tab will show all messages and replies in the order they were sent. With the time stamp at the bottom of that message, and the phone number the message came from. The phone number and sent time need to be gray. ( #666666 )

2- The yellow message bubbles ( #fcffb8ff ) are messages that have not been seen. The light gray messages ( #f3f3f3ff ) are messages that have been seen. This feature already exists, just update message colors if needed. The reply message will always be blue. ( #8dd5f5ff )

3- The text for incoming messages need to be black, and the text for outgoing messages needs to be white.

4- Until we get profile pictures, use....
![profile_placeholder](https://cloud.githubusercontent.com/assets/25572175/24840773/c9babc54-1d28-11e7-8caa-02b10d1d231e.png)

![image](https://cloud.githubusercontent.com/assets/25572175/24841034/5cd47a4c-1d2f-11e7-8b42-feed73d6e3a6.png)

5- Once the user clicks on a text message, or profile image, ONLY the conversation between the user clicked on and the one who clicked on it should show. Just like a normal texting app. 

6- The message bubbles will now always be gray ( #d9d9d9ff ) with black text on the left side (receiving) and blue ( #8dd5f5ff ) with white text on the right side (sending). With the time it was sent at the bottom of that message still. 

7- We need to mark the difference between the days. For previous days, put the date (ex: 4/2/2017 ), if the messages are from today, put Today . Divide it exactly how I did in the mock up with two lines and the date information in the middle, centered. 

8- This page will open up with the keyboard not showing, but once the user clicks the box to type, the Android keyboard will come up, and the words 'Type message' (in gray #999999 ) will disappear so only the cursor is showing and the outline is blue ( #3ab8e8 ). As the users message gets bigger, the box show grow. The color of the typing box will be #f3f3f3ff .

9- The send button is.  Please make the send button gray and disabled if no text is entered into the text field.  Turn button blue as shown below and enable if text is entered.  This prevent user from sending blank message.
![image](https://cloud.githubusercontent.com/assets/25572175/24841086/667fcd34-1d30-11e7-83bc-4495cf3d9554.png)

10- The back button at the top of the page next to the phone number takes user back to the Message Tab.

![image](https://cloud.githubusercontent.com/assets/25572175/24841129/2bd523a4-1d31-11e7-8805-53c2a59b41a3.png)

**Comment by SarahGarren** [comment]
@Nomanghous 

1- When the message opens, it opens to the very top of the conversation. It should open to the very last message sent/received.
 
![image](https://cloud.githubusercontent.com/assets/25572175/25261121/890ea18a-2605-11e7-9dd0-9edb46275994.png)

2- The back icon the tablet has needs to not work or if you can't make it not work, make it take user back to Message Tab.

![image](https://cloud.githubusercontent.com/assets/25572175/25261311/4a5b8e02-2606-11e7-8200-be16da849a44.png)

3- Please make the back button at the top thicker.

![image](https://cloud.githubusercontent.com/assets/25572175/25261498/e3f88362-2606-11e7-9c6b-39b6d397d55b.png)

4- There is no send button to send the types out message reply.

![image](https://cloud.githubusercontent.com/assets/25572175/25261535/22259378-2607-11e7-93c8-d887557a8d32.png)

5- After user clicks the down arrow that make the keyboard disappear, the text box still has the blue outline and cursor. It should go back to gray and say 'Type Message'.

![image](https://cloud.githubusercontent.com/assets/25572175/25261675/f80cf260-2607-11e7-9a46-979d30b241d9.png)

the down arrow-
![image](https://cloud.githubusercontent.com/assets/25572175/25261686/155cffae-2608-11e7-81ef-02d9cedb374c.png)

6- when the keyboard is up, please make the blue ext box visible.

![image](https://cloud.githubusercontent.com/assets/25572175/25261904/80885bc4-2609-11e7-9b49-e2614f03cfa0.png)

**Comment by Nomanghous** [comment]
UPDATE: I am working on this and fixed almost all of them. But for point no 9 can you  please make a method that will return only one message of following type of json.
"Id":42074,
            "MessageType":0,
            "ToUserId":10,
            "ToUsername":"IPS04",
            "ToUser":"IPS04",
            "ToPhone":"",
            "FromUserId":1,
            "FromUsername":"brianklim",
            "FromUser":"BrianLim",
            "FromPhone":"(310)528-2301",
            "Subject":"Sentry BroadcastMsg",
            "Body":"Pickup Request: 1 rider(s) at brianklim",
            "Sent":"\/Date(1486580643267)\/",
            "SentTimeSpan":"68d  ago",
            "Read":"\/Date(1492151301770)\/"

**Comment by Brianklim** [comment]
Hey @Nomanghous   You're currently retrieving messages every 5 seconds.  Can you parse that json response and if "FromUserId" is the same as the FromUserId of the open conversation then append the new message.

**Comment by Nomanghous** [comment]
yes i am doing exactly like this but for the conversation messages the response type is different than inbox messages. So the schema i have sent above should be followed.

**Comment by Nomanghous** [comment]
Inbox Messages have json response like this:
"id":42089,
      "type":"in",
      "toUserId":10,
      "fromUserId":1,
      "fromContactCell":"(310)528-2301",
      "subject":"Sentry BroadcastMsg",
      "body":"Pickup Request: 2 rider(s) at brianklim",
      "sentTimestamp":"\/Date(1486590755757)\/",
      "sent":"9:52 PM",
      "read":"10:11 AM"

but i need this:
"Id":42074,
"MessageType":0,
"ToUserId":10,
"ToUsername":"IPS04",
"ToUser":"IPS04",
"ToPhone":"",
"FromUserId":1,
"FromUsername":"brianklim",
"FromUser":"BrianLim",
"FromPhone":"(310)528-2301",
"Subject":"Sentry BroadcastMsg",
"Body":"Pickup Request: 1 rider(s) at brianklim",
"Sent":"/Date(1486580643267)/",
"SentTimeSpan":"68d ago",
"Read":"/Date(1492151301770)/"

**Comment by Brianklim** [comment]
Hey @Nomanghous , I think I understand.  You want similar schema that you got when you first build the conversation page.  However, you are already receiving messages in the Message Inbox by posting every 5 seconds.  If you want the new format then I either have to 1) change the response for Inbox Messages (which may break message for older version tablets) or 2) create a new api for conversation and you post every 5 seconds.  (this would be in addition to the every 5 second for the message inbox).

Rather than do all that, why can't you just use the inbox message response?  You got fromUserId, fromContactCell, sentTimestamp, and body.  Let me know if you can do this.  I'm trying to make little change as possible so that we don't break anything.  If not possible, I would rather do option 1 above instead of option 2.

**Comment by Nomanghous** [comment]
@Brianklim I have seen that now, please let me know that if there is any difference between inbox messages and conversation messages?  
"Message Inbox by posting every 5 seconds." is this getting the conversation messages as well? or just inbox ?

**Comment by Brianklim** [comment]
@Nomanghous , the inbox gets all messages to tablet user.  conversation message is messages just between tablet user and a specified user (based on the message you tap).

Yes, the Message Inbox message response also gets the conversation message as well.  It gets everything.  So you just need to check if new messages coming to inbox is part of the conversation.  I hope this makes sense.

**Comment by Nomanghous** [comment]
Okay please let me know how could i test this ? is there any way that i can send new messages to test this ?

**Comment by Brianklim** [comment]
yeah.  you can use two users.  IPS03 and IPS04.  They have a conversation between each other so you can just reply on the tablets.  use the dev environment (dev::IPS03 and dev::IPS04)

**Comment by Nomanghous** [comment]
okay sure i will try that  and let you know. Thanks a lot for your time.

**Comment by Brianklim** [comment]
Thanks.

**Comment by Nomanghous** [comment]
@Brianklim one thing is missing from that response. We will need sentTimestamp as well. This key is missing from incoming messages json, please add this field as well.

**Comment by Brianklim** [comment]
@Nomanghous can you use "Sent" value?

**Comment by Nomanghous** [comment]
Sent value is just a string of time only. date is not in it.

**Comment by Brianklim** [comment]
What about "sentTimestamp"

**Comment by Nomanghous** [comment]
"sentTimestamp" is missing "Sentry/GetUnreadMessages", i have seen that in "Sentry/GetMessages"

**Comment by Brianklim** [comment]
okay. so you need sentTimestamp added to GetUnreadMessages, correct?

**Comment by Nomanghous** [comment]
yeah...

**Comment by Brianklim** [comment]
okay. i'll add this later tonight.

**Comment by Nomanghous** [comment]
okay great! Thank you. Going to sleep, Good night bro.

**Comment by Brianklim** [comment]
"sentTimestamp" has been added

**Comment by SarahGarren** [comment]
@Nomanghous 

Right now the Message Tab only shows all the messages received. When the user is on the Message Tab and not in a conversation, every message sent and received needs to show in order. 

![image](https://cloud.githubusercontent.com/assets/25572175/25318835/060719dc-284b-11e7-8806-0909ec395bbc.png)

**Comment by Nomanghous** [comment]
@Brianklim  @SarahGarren  Actually this Sentry/GetMessages URL is sending incoming message only, it's not sending out going.

**Comment by SarahGarren** [comment]
@Nomanghous 

When user is on the Message Tab and clicks on a message they sent (a blue bubble) the conversation that the message was sent in needs to come up, just like when the user clicks on a received message. Right now it doesn't do anything. Please fix.

**Comment by SarahGarren** [comment]
@

1- Right now, when a private conversation is opened, the text box at the bottom of the screen has a blue outline and cursor. Please fix this so when user first opens the conversation it is all gray with the words "Type Message".
![image](https://cloud.githubusercontent.com/assets/25572175/25512782/19e88f2a-2b85-11e7-8235-807bba853422.png)

2- Right now, on the Message Tab, when a gray bubble (received message) is clicked on, and the private conversation comes up the number comes up at the top of the conversation. Good! BUT if a blue bubble (sent message) is clicked on on the Message Tab, the number doesn't come up at the top of the conversation. Please change this so when either blue or gray is clicked on, the number comes up at the top of the conversation. 
![image](https://cloud.githubusercontent.com/assets/25572175/25512825/713cde70-2b85-11e7-9363-e72edeae913e.png)

3- On the Message Tab, if either the blue or gray bubbles are clicked on the conversation between the two users does not show up, please fix this bug so every time a bubble is clicked on the conversation between the two users comes up. 
![image](https://cloud.githubusercontent.com/assets/25572175/25512982/8b011fb4-2b86-11e7-8bb2-68b049f1d8e3.png)

4- The placement of received messages on the Message Tab is bad. It was fine in the last apk. Please align to the left said. 
![image](https://cloud.githubusercontent.com/assets/25572175/25513057/2bb59a70-2b87-11e7-8fd2-3fb3f3792cbb.png)

5- When a private conversation is opened, the dates they were sent are wrong. Test-test5 were all sent today but it is saying they were sent on the 25th of April. This happens when I open a conversation, send a message to another tablet, go back to Message Tab, then back into the conversation. It only says the most recent message was sent today. Please fix it so the dates are the correct days they were sent.
![image](https://cloud.githubusercontent.com/assets/25572175/25513318/2ba4570e-2b89-11e7-9bbb-708f47efdf02.png)

6- The tablet receiving messages isn't make a noise when a new message comes in, it only makes a noise when the user has Message Tab open. It needs to always make a noise when the user is on the app. 

7- When user opens Message Tab and there is a new message, the bubble should be yellow until the user clicks on that conversation. Right now, it is only yellow when the user is on the Message Tab when the message comes in. This needs to act like a confirmation that the user saw the message. 

8- When the user is on a different Tab, not only should the tablet make a noise, the alert bubble should one up on the Message Tab icon, which it does. Good! BUT when the user clicks on the Message Tab to see what the new message is, the alert bubble should go away. And if user is on the Message Tab, when  new message comes in, the tablet should make a noise but the alert bubble shouldn't come up.
![image](https://cloud.githubusercontent.com/assets/25572175/25513522/778b2cc8-2b8a-11e7-8e04-a2363c279a3b.png)

**Comment by Brianklim** [comment]
creating new bug tickets because this ticket is getting too long.
